server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8001/3835PPTSplit?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 10000
      minimum-idle: 3
  mvc:
    static-path-pattern: /local-resource/**
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  web:
    resources:
      static-locations: file:${resource-location}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.web: DEBUG
    java.sql: DEBUG

resource-location: /3835pptserver/service/ppt