server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://172.20.196.57:3306/3835PPTX?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 11223366zxl
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 10000
      minimum-idle: 3
  mvc:
    static-path-pattern: /local-resource/**
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MBapplication.yml
  web:
    resources:
      static-locations: file:${resource-location}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.web: DEBUG
    java.sql: DEBUG

resource-location: D:\work\java\3835\pptSplit